# Ejemplo de condicionales
steps:
  - command: "./build.sh"
    label: "Compilar"
    artifact_paths:
      - "build/*"
  - wait
  - command: "./backup.sh"
    label: "Archivado backup"
  - command: "./test.sh"
    label: "Tests"
  - wait
  - command: "./deploy.sh"
    label: "Desplegar"
