# Ejemplo de dependencias
steps:
  - command: "./build.sh"
    label: "Compilar"
    key: "build"
    artifact_paths:
      - "build/*"
  - command: "./backup.sh"
    label: "Archivado backup"
    key: "backup"
    depends_on: "build"
  - command: "./test.sh functional"
    label: "Tests Funcionales"
    key: "functional"
    depends_on: "build"
  - command: "./test.sh unit"
    label: "Tests Unitarios"
    key: "unit"
    depends_on: "build"
  - command: "./test.sh load"
    label: "Tests de carga"
    key: "load"
    depends_on: "build"
  - command: "./deploy.sh"
    label: "Desplegar"
    key: "deploy"
    depends_on:
      - "unit"
      - "functional"
